-- ============================================================
-- UniPass - Supabase PostgreSQL Setup Script
-- ਇਹ script Supabase Dashboard > SQL Editor ਵਿੱਚ run ਕਰੋ
-- ============================================================

-- 1. Visitors Table
CREATE TABLE IF NOT EXISTS visitors (
    id              SERIAL PRIMARY KEY,
    name            VARCHAR(100) NOT NULL,
    phone_number    VARCHAR(15)  NOT NULL,
    host_department VARCHAR(100) NOT NULL,
    purpose_details TEXT         NOT NULL,
    status          VARCHAR(20)  DEFAULT 'Pending' CHECK (status IN ('Pending', 'Inside', 'Checked Out', 'Rejected')),
    time_in         TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    time_out        TIMESTAMP    NULL,
    daily_seq       INTEGER      NULL,
    entered_by      VARCHAR(50)  NULL
);

-- 2. Users Table (Authentication + RBAC)
CREATE TABLE IF NOT EXISTS users (
    id            SERIAL PRIMARY KEY,
    username      VARCHAR(50)  UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role          VARCHAR(20)  NOT NULL CHECK (role IN ('admin', 'gate')),
    created_at    TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);

-- 3. Seed default users
-- NOTE: password for 'admin' = 'admin', password for 'gate' = 'gate'
-- These hashes are generated by PHP password_hash() — run seed.php instead for fresh hashes.
-- Or run seed.php via browser: http://localhost:8000/seed.php (it will auto-detect Supabase)
