services:
  - type: web
    name: unipass
    runtime: docker
    plan: free
    branch: main
    healthCheckPath: /login.php
    envVars:
      - key: DATABASE_URL
        value: mysql://44Hq83chaYcfhH4.root:sOQIKKdgdiIJ9OAo@gateway01.ap-northeast-1.prod.aws.tidbcloud.com:4000/sys
      - key: FORCE_TIDB_CLOUD
        value: "true"
