services:
  - type: web
    name: unipass
    runtime: docker
    plan: free
    branch: main
    healthCheckPath: /login.php
    envVars:
      - key: FORCE_TIDB_CLOUD
        value: "true"
      - key: TIDB_HOST
        value: gateway01.ap-northeast-1.prod.aws.tidbcloud.com
      - key: TIDB_PORT
        value: "4000"
      - key: TIDB_NAME
        value: vms_db
      - key: TIDB_USER
        value: 44Hq83chaYcfhH4.root
      - key: TIDB_PASS
        value: sOQIKKdgdiIJ9OAo
